// The AIR classes the player declares itself, since the oracle's playerglobal
// predates them: their .as files under packages/player/src/playerglobal,
// compiled by ASC in the oracle's container against builtin and playerglobal
// into one ABC, which air-library.ts there holds. With --update it writes
// that file; the unit tests compile again and compare.
//
//   node tests/player/air-library.ts [--update]
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { runOracle } from "../../oracle/oracle.ts";

const here = fileURLToPath(new URL(".", import.meta.url));
const root = fileURLToPath(new URL("../../", import.meta.url));
const playerglobal = "packages/player/src/playerglobal/";
const SOURCES = ["air/net/WebSocket.as", "flash/events/WebSocketEvent.as"];
export const GENERATED = `${root}${playerglobal}air-library.ts`;

// U+E294, API version 0 (VM_ALLVERSIONS), in UTF-8. Loaded as a builtin, an
// unmarked URI that playerglobal marks, flash.events or the empty one, is
// VM-internal and hidden from the SWF's code; marked so, every version sees
// the names. What the library's own code finds through them, Object, Event
// and ByteArray's members, playerglobal leaves unmarked too.
const MARK = [0xee, 0x8a, 0x94];
const CONSTANT_PackageNamespace = 0x16;

/** The library's ABC, compiled into `out`; throws with ASC's log if it does not compile. */
export function compileAirLibrary(out = `${here}out/air-library/`): Uint8Array {
  // ASC's other files as the container sees them, from the repository's root.
  const [main, ...rest] = SOURCES.map((s) => `${playerglobal}${s}`);
  const [result] = runOracle(
    [{ source: `${root}${main}`, ascArgs: rest.flatMap((s) => ["-in", s]) }],
    out,
    { imports: ["builtin", "playerglobal"], run: false },
  );
  if (!result.compiled) {
    throw new Error(`the AIR library did not compile:\n${result.compileLog}`);
  }

  return markPublic(new Uint8Array(readFileSync(`${out}${result.name}.abc`)));
}

/**
 * The ABC with each public namespace's URI marked: a marked copy of each
 * such string added to the string pool, which the namespace names instead,
 * so that the string's other uses keep it unmarked.
 */
function markPublic(abc: Uint8Array): Uint8Array {
  let at = 4;
  const u30 = () => {
    let value = 0;
    for (let shift = 0; shift < 35; shift += 7) {
      const byte = abc[at++];
      value += (byte & 0x7f) * 2 ** shift;
      if (!(byte & 0x80)) {
        break;
      }
    }

    return value;
  };
  const each = (read: (i: number) => void) => {
    const count = u30();
    for (let i = 1; i < count; i++) {
      read(i);
    }

    return count;
  };

  each(u30);
  each(u30);
  each(() => {
    at += 8;
  });
  const stringsAt = at;
  const strings: Uint8Array[] = [];
  const stringCount = each(() => {
    const length = u30();
    strings.push(abc.subarray(at, at + length));
    at += length;
  });
  const stringsEnd = at;

  const namespaces: [number, number][] = [];
  each(() => {
    namespaces.push([abc[at++], u30()]);
  });
  const namespacesEnd = at;

  // One marked copy per string, indexed after the pool's own.
  const marked = new Map<number, number>();
  for (const ns of namespaces) {
    if (ns[0] === CONSTANT_PackageNamespace && ns[1] !== 0) {
      if (!marked.has(ns[1])) {
        marked.set(ns[1], Math.max(stringCount, 1) + marked.size);
      }

      ns[1] = marked.get(ns[1]) as number;
    }
  }

  const parts: number[][] = [];
  const bytes = (b: ArrayLike<number>) => parts.push(Array.from(b));
  bytes(abc.subarray(0, stringsAt));
  bytes(u30Bytes(Math.max(stringCount, 1) + marked.size));
  bytes(abc.subarray(stringsAt + u30Bytes(stringCount).length, stringsEnd));
  for (const index of marked.keys()) {
    const text = strings[index - 1];
    bytes(u30Bytes(text.length + MARK.length));
    bytes(text);
    bytes(MARK);
  }

  bytes(u30Bytes(namespaces.length + 1));
  for (const [kind, name] of namespaces) {
    bytes([kind]);
    bytes(u30Bytes(name));
  }

  bytes(abc.subarray(namespacesEnd));
  return new Uint8Array(parts.flat());
}

function u30Bytes(value: number): number[] {
  const bytes: number[] = [];
  do {
    bytes.push((value & 0x7f) | (value > 0x7f ? 0x80 : 0));
    value >>>= 7;
  } while (value);

  return bytes;
}

/** air-library.ts as it should be for `abc`. */
export function generated(abc: Uint8Array): string {
  return `// AIR's air.net.WebSocket and flash.events.WebSocketEvent, declared for
// the player: the ABC compiled from the .as files beside their natives.
// Generated by tests/player/air-library.ts; not to be edited.

/**
 * An ABC to load after builtin and playerglobal (Scripting.loadLibraries),
 * for SWFs that use AIR 51's WebSocket client.
 */
export const airLibrary: Uint8Array = Uint8Array.from(
  atob(
    "${Buffer.from(abc).toString("base64")}",
  ),
  (c) => c.charCodeAt(0),
);
`;
}

if (import.meta.main) {
  const text = generated(compileAirLibrary());
  if (process.argv.includes("--update")) {
    writeFileSync(GENERATED, text);
  } else if (readFileSync(GENERATED, "utf8") !== text) {
    console.log(`${GENERATED} is out of date: run with --update`);
    process.exit(1);
  }
}
