import type { ClassDecl } from "../../declare.js";

export const Vector$objectDecl = {
  name: "internal:__AS3__.vec::Vector$object",
  super: "Object",
  final: true,
  init: {
    params: [
      ["uint", ["int", 0]],
      ["Boolean", ["boolean", false]],
    ],
    avmplus: true,
  },
  classInit: { avmplus: true },
  static: [
    {
      method: "private::castToThisType",
      final: true,
      params: ["*"],
      returns: "{internal:__AS3__.vec}::Vector$object",
      avmplus: true,
    },
    {
      method: "private::_every",
      final: true,
      params: ["*", "Function", "*"],
      returns: "Boolean",
      native: true,
    },
    {
      method: "private::_forEach",
      final: true,
      params: ["*", "Function", "*"],
      returns: "void",
      native: true,
    },
    {
      method: "private::_some",
      final: true,
      params: ["*", "Function", "*"],
      returns: "Boolean",
      native: true,
    },
    { method: "private::_sort", final: true, params: ["*", "Array"], native: true },
  ],
  instance: [
    {
      method: "private::newThisType",
      returns: "{internal:__AS3__.vec}::Vector$object",
      native: true,
    },
    { get: "length", returns: "uint", native: true },
    { set: "length", params: ["uint"], native: true },
    { set: "fixed", params: ["Boolean"], native: true },
    { get: "fixed", returns: "Boolean", native: true },
    { method: "AS3::toString", returns: "String", avmplus: true },
    { method: "AS3::toLocaleString", returns: "String", avmplus: true },
    {
      method: "AS3::join",
      params: [["String", ["string", ","]]],
      returns: "String",
      avmplus: true,
    },
    { method: "private::_concat", params: ["Array"], avmplus: true },
    {
      method: "AS3::every",
      params: ["Function", ["Object", ["null", null]]],
      returns: "Boolean",
      avmplus: true,
    },
    {
      method: "AS3::forEach",
      params: ["Function", ["Object", ["null", null]]],
      returns: "void",
      avmplus: true,
    },
    { method: "AS3::map", params: ["Function", ["Object", ["null", null]]], avmplus: true },
    { method: "AS3::push", returns: "uint", rest: true, native: true },
    { method: "private::_reverse", returns: "void", native: true },
    {
      method: "AS3::some",
      params: ["*", ["Object", ["null", null]]],
      returns: "Boolean",
      avmplus: true,
    },
    {
      method: "private::_slice",
      params: [
        ["Number", ["int", 0]],
        ["Number", ["int", 2147483647]],
      ],
      avmplus: true,
    },
    { method: "private::_splice", params: ["*", "*", "Array"], avmplus: true },
    {
      method: "private::_spliceHelper",
      params: ["uint", "uint", "uint", "Object", "uint"],
      returns: "void",
      native: true,
    },
    { method: "AS3::unshift", returns: "uint", rest: true, native: true },
    { method: "private::_filter", params: ["Function", "*"], native: true },
    { method: "private::_map", params: ["Function", "*"], native: true },
    { method: "private::clamp", params: ["Number", "uint"], returns: "uint", avmplus: true },
    {
      method: "AS3::concat",
      returns: "{internal:__AS3__.vec}::Vector$object",
      rest: true,
      avmplus: true,
    },
    {
      method: "AS3::filter",
      params: ["Function", ["Object", ["null", null]]],
      returns: "{internal:__AS3__.vec}::Vector$object",
      avmplus: true,
    },
    { method: "AS3::pop", native: true },
    { method: "AS3::reverse", returns: "{internal:__AS3__.vec}::Vector$object", avmplus: true },
    { method: "AS3::shift", native: true },
    {
      method: "AS3::slice",
      params: [
        ["Number", ["int", 0]],
        ["Number", ["int", 2147483647]],
      ],
      returns: "{internal:__AS3__.vec}::Vector$object",
      avmplus: true,
    },
    {
      method: "AS3::sort",
      params: ["*"],
      returns: "{internal:__AS3__.vec}::Vector$object",
      avmplus: true,
    },
    {
      method: "AS3::splice",
      params: ["Number", "Number"],
      returns: "{internal:__AS3__.vec}::Vector$object",
      rest: true,
      avmplus: true,
    },
    {
      method: "AS3::insertAt",
      params: ["int", "Object"],
      returns: "void",
      native: true,
      meta: [["API", [["", "708"]]]],
    },
    {
      method: "AS3::removeAt",
      params: ["int"],
      returns: "Object",
      native: true,
      meta: [["API", [["", "708"]]]],
    },
    {
      method: "AS3::indexOf",
      params: ["Object", ["Number", ["int", 0]]],
      returns: "Number",
      avmplus: true,
    },
    {
      method: "AS3::lastIndexOf",
      params: ["Object", ["Number", ["int", 2147483647]]],
      returns: "Number",
      avmplus: true,
    },
  ],
} as const satisfies ClassDecl;
