// ByteArray, as SWFs link against it (see ../../../declare.ts).

import type { ClassDecl } from "../../../declare.js";

export const ByteArrayClass: ClassDecl = {
  name: "flash.utils::ByteArray",
  super: "Object",
  interfaces: ["internal:flash.utils::IDataInput2", "internal:flash.utils::IDataOutput2"],
  sealed: true,
  init: { avmplus: true },
  classInit: { avmplus: true },
  static: [
    { get: "defaultObjectEncoding", final: true, returns: "uint", native: true },
    { set: "defaultObjectEncoding", final: true, params: ["uint"], returns: "void", native: true },
    { var: "private::_defaultObjectEncoding", type: "uint" },
  ],
  instance: [
    {
      method: "readBytes",
      params: ["flash.utils::ByteArray", ["uint", ["int", 0]], ["uint", ["int", 0]]],
      returns: "void",
      native: true,
    },
    {
      method: "writeBytes",
      params: ["flash.utils::ByteArray", ["uint", ["int", 0]], ["uint", ["int", 0]]],
      returns: "void",
      native: true,
    },
    { method: "writeBoolean", params: ["Boolean"], returns: "void", native: true },
    { method: "writeByte", params: ["int"], returns: "void", native: true },
    { method: "writeShort", params: ["int"], returns: "void", native: true },
    { method: "writeInt", params: ["int"], returns: "void", native: true },
    { method: "writeUnsignedInt", params: ["uint"], returns: "void", native: true },
    { method: "writeFloat", params: ["Number"], returns: "void", native: true },
    { method: "writeDouble", params: ["Number"], returns: "void", native: true },
    { method: "writeMultiByte", params: ["String", "String"], returns: "void", native: true },
    { method: "writeUTF", params: ["String"], returns: "void", native: true },
    { method: "writeUTFBytes", params: ["String"], returns: "void", native: true },
    { method: "readBoolean", returns: "Boolean", native: true },
    { method: "readByte", returns: "int", native: true },
    { method: "readUnsignedByte", returns: "uint", native: true },
    { method: "readShort", returns: "int", native: true },
    { method: "readUnsignedShort", returns: "uint", native: true },
    { method: "readInt", returns: "int", native: true },
    { method: "readUnsignedInt", returns: "uint", native: true },
    { method: "readFloat", returns: "Number", native: true },
    { method: "readDouble", returns: "Number", native: true },
    { method: "readMultiByte", params: ["uint", "String"], returns: "String", native: true },
    { method: "readUTF", returns: "String", native: true },
    { method: "readUTFBytes", params: ["uint"], returns: "String", native: true },
    { get: "length", returns: "uint", native: true },
    { set: "length", params: ["uint"], returns: "void", native: true },
    { method: "writeObject", params: ["*"], returns: "void", native: true },
    { method: "readObject", native: true },
    { method: "deflate", returns: "void", avmplus: true, api: 2, meta: [["API", [["", "662"]]]] },
    { method: "private::_compress", params: ["String"], returns: "void", native: true },
    {
      method: "compress",
      params: [["String", ["string", "zlib"]]],
      returns: "void",
      avmplus: true,
    },
    { method: "inflate", returns: "void", avmplus: true, api: 2, meta: [["API", [["", "662"]]]] },
    { method: "private::_uncompress", params: ["String"], returns: "void", native: true },
    {
      method: "uncompress",
      params: [["String", ["string", "zlib"]]],
      returns: "void",
      avmplus: true,
    },
    { method: "toString", returns: "String", avmplus: true },
    { method: "private::_toString", returns: "String", native: true },
    { get: "bytesAvailable", returns: "uint", native: true },
    { get: "position", returns: "uint", native: true },
    { set: "position", params: ["uint"], returns: "void", native: true },
    { get: "objectEncoding", returns: "uint", native: true },
    { set: "objectEncoding", params: ["uint"], returns: "void", native: true },
    { get: "endian", returns: "String", native: true },
    { set: "endian", params: ["String"], returns: "void", native: true },
    { method: "clear", returns: "void", native: true, api: 2, meta: [["API", [["", "662"]]]] },
    {
      method: "atomicCompareAndSwapIntAt",
      params: ["int", "int", "int"],
      returns: "int",
      native: true,
      api: 22,
      meta: [["API", [["", "682"]]]],
    },
    {
      method: "atomicCompareAndSwapLength",
      params: ["int", "int"],
      returns: "int",
      native: true,
      api: 22,
      meta: [["API", [["", "682"]]]],
    },
    { get: "shareable", returns: "Boolean", native: true, api: 22, meta: [["API", [["", "682"]]]] },
    {
      set: "shareable",
      params: ["Boolean"],
      returns: "void",
      native: true,
      api: 22,
      meta: [["API", [["", "682"]]]],
    },
  ],
};
