// Date, as SWFs link against it (see ../declare.ts).

import type { ClassDecl } from "../declare.js";

export const DateClass: ClassDecl = {
  name: "Date",
  super: "Object",
  init: {
    params: [
      ["*", ["undefined", null]],
      ["*", ["undefined", null]],
      ["*", ["undefined", null]],
      ["*", ["undefined", null]],
      ["*", ["undefined", null]],
      ["*", ["undefined", null]],
      ["*", ["undefined", null]],
    ],
    avmplus: true,
  },
  classInit: { avmplus: true },
  static: [
    { const: "length", type: "int", value: ["int", 7] },
    { method: "parse", final: true, params: ["*"], returns: "Number", native: true },
    {
      method: "UTC",
      final: true,
      params: [
        "*",
        "*",
        ["*", ["int", 1]],
        ["*", ["int", 0]],
        ["*", ["int", 0]],
        ["*", ["int", 0]],
        ["*", ["int", 0]],
      ],
      returns: "Number",
      rest: true,
      native: true,
    },
  ],
  instance: [
    { method: "AS3::valueOf", returns: "Number", native: true },
    { method: "private::_toString", params: ["int"], returns: "String", native: true },
    { method: "private::_setTime", params: ["Number"], returns: "Number", native: true },
    { method: "private::_get", params: ["int"], returns: "Number", native: true },
    {
      method: "AS3::setTime",
      params: [["*", ["undefined", null]]],
      returns: "Number",
      avmplus: true,
    },
    { method: "AS3::toString", returns: "String", avmplus: true },
    { method: "AS3::toDateString", returns: "String", avmplus: true },
    { method: "AS3::toTimeString", returns: "String", avmplus: true },
    { method: "AS3::toLocaleString", returns: "String", avmplus: true },
    { method: "AS3::toLocaleDateString", returns: "String", avmplus: true },
    { method: "AS3::toLocaleTimeString", returns: "String", avmplus: true },
    { method: "AS3::toUTCString", returns: "String", avmplus: true },
    { method: "AS3::getUTCFullYear", returns: "Number", native: true },
    { method: "AS3::getUTCMonth", returns: "Number", native: true },
    { method: "AS3::getUTCDate", returns: "Number", native: true },
    { method: "AS3::getUTCDay", returns: "Number", native: true },
    { method: "AS3::getUTCHours", returns: "Number", native: true },
    { method: "AS3::getUTCMinutes", returns: "Number", native: true },
    { method: "AS3::getUTCSeconds", returns: "Number", native: true },
    { method: "AS3::getUTCMilliseconds", returns: "Number", native: true },
    { method: "AS3::getFullYear", returns: "Number", native: true },
    { method: "AS3::getMonth", returns: "Number", native: true },
    { method: "AS3::getDate", returns: "Number", native: true },
    { method: "AS3::getDay", returns: "Number", native: true },
    { method: "AS3::getHours", returns: "Number", native: true },
    { method: "AS3::getMinutes", returns: "Number", native: true },
    { method: "AS3::getSeconds", returns: "Number", native: true },
    { method: "AS3::getMilliseconds", returns: "Number", native: true },
    { method: "AS3::getTimezoneOffset", returns: "Number", native: true },
    { method: "AS3::getTime", returns: "Number", native: true },
    { method: "private::_setFullYear", returns: "Number", rest: true, native: true },
    { method: "private::_setMonth", returns: "Number", rest: true, native: true },
    { method: "private::_setDate", returns: "Number", rest: true, native: true },
    { method: "private::_setHours", returns: "Number", rest: true, native: true },
    { method: "private::_setMinutes", returns: "Number", rest: true, native: true },
    { method: "private::_setSeconds", returns: "Number", rest: true, native: true },
    { method: "private::_setMilliseconds", returns: "Number", rest: true, native: true },
    { method: "private::_setUTCFullYear", returns: "Number", rest: true, native: true },
    { method: "private::_setUTCMonth", returns: "Number", rest: true, native: true },
    { method: "private::_setUTCDate", returns: "Number", rest: true, native: true },
    { method: "private::_setUTCHours", returns: "Number", rest: true, native: true },
    { method: "private::_setUTCMinutes", returns: "Number", rest: true, native: true },
    { method: "private::_setUTCSeconds", returns: "Number", rest: true, native: true },
    { method: "private::_setUTCMilliseconds", returns: "Number", rest: true, native: true },
    {
      method: "AS3::setFullYear",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setMonth",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setDate",
      params: [["*", ["undefined", null]]],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setHours",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setMinutes",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setSeconds",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setMilliseconds",
      params: [["*", ["undefined", null]]],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setUTCFullYear",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setUTCMonth",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setUTCDate",
      params: [["*", ["undefined", null]]],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setUTCHours",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setUTCMinutes",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setUTCSeconds",
      params: [
        ["*", ["undefined", null]],
        ["*", ["undefined", null]],
      ],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    {
      method: "AS3::setUTCMilliseconds",
      params: [["*", ["undefined", null]]],
      returns: "Number",
      arguments: true,
      avmplus: true,
    },
    { get: "fullYear", returns: "Number", avmplus: true },
    { set: "fullYear", params: ["Number"], avmplus: true },
    { get: "month", returns: "Number", avmplus: true },
    { set: "month", params: ["Number"], avmplus: true },
    { get: "date", returns: "Number", avmplus: true },
    { set: "date", params: ["Number"], avmplus: true },
    { get: "hours", returns: "Number", avmplus: true },
    { set: "hours", params: ["Number"], avmplus: true },
    { get: "minutes", returns: "Number", avmplus: true },
    { set: "minutes", params: ["Number"], avmplus: true },
    { get: "seconds", returns: "Number", avmplus: true },
    { set: "seconds", params: ["Number"], avmplus: true },
    { get: "milliseconds", returns: "Number", avmplus: true },
    { set: "milliseconds", params: ["Number"], avmplus: true },
    { get: "fullYearUTC", returns: "Number", avmplus: true },
    { set: "fullYearUTC", params: ["Number"], avmplus: true },
    { get: "monthUTC", returns: "Number", avmplus: true },
    { set: "monthUTC", params: ["Number"], avmplus: true },
    { get: "dateUTC", returns: "Number", avmplus: true },
    { set: "dateUTC", params: ["Number"], avmplus: true },
    { get: "hoursUTC", returns: "Number", avmplus: true },
    { set: "hoursUTC", params: ["Number"], avmplus: true },
    { get: "minutesUTC", returns: "Number", avmplus: true },
    { set: "minutesUTC", params: ["Number"], avmplus: true },
    { get: "secondsUTC", returns: "Number", avmplus: true },
    { set: "secondsUTC", params: ["Number"], avmplus: true },
    { get: "millisecondsUTC", returns: "Number", avmplus: true },
    { set: "millisecondsUTC", params: ["Number"], avmplus: true },
    { get: "time", returns: "Number", avmplus: true },
    { set: "time", params: ["Number"], avmplus: true },
    { get: "timezoneOffset", returns: "Number", avmplus: true },
    { get: "day", returns: "Number", avmplus: true },
    { get: "dayUTC", returns: "Number", avmplus: true },
  ],
};
