// Math, as SWFs link against it (see ../declare.ts).

import type { ClassDecl } from "../declare.js";

export const MathClass: ClassDecl = {
  name: "Math",
  super: "Object",
  sealed: true,
  final: true,
  init: { avmplus: true },
  classInit: { avmplus: true },
  static: [
    { const: "E", type: "Number", value: ["double", Math.E] },
    { const: "LN10", type: "Number", value: ["double", Math.LN10] },
    { const: "LN2", type: "Number", value: ["double", Math.LN2] },
    { const: "LOG10E", type: "Number", value: ["double", Math.LOG10E] },
    { const: "LOG2E", type: "Number", value: ["double", Math.LOG2E] },
    { const: "PI", type: "Number", value: ["double", Math.PI] },
    { const: "SQRT1_2", type: "Number", value: ["double", Math.SQRT1_2] },
    { const: "SQRT2", type: "Number", value: ["double", Math.SQRT2] },
    {
      method: "private::_min",
      final: true,
      params: ["Number", "Number"],
      returns: "Number",
      native: true,
    },
    {
      method: "private::_max",
      final: true,
      params: ["Number", "Number"],
      returns: "Number",
      native: true,
    },
    { method: "abs", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "acos", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "asin", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "atan", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "ceil", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "cos", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "exp", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "floor", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "log", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "round", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "sin", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "sqrt", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "tan", final: true, params: ["Number"], returns: "Number", native: true },
    { method: "atan2", final: true, params: ["Number", "Number"], returns: "Number", native: true },
    { method: "pow", final: true, params: ["Number", "Number"], returns: "Number", native: true },
    { const: "private::NegInfinity", type: "Number", value: ["double", "-Infinity"] },
    {
      method: "max",
      final: true,
      params: [
        ["Number", ["double", "-Infinity"]],
        ["Number", ["double", "-Infinity"]],
      ],
      returns: "Number",
      rest: true,
      native: true,
    },
    {
      method: "min",
      final: true,
      params: [
        ["Number", ["double", "Infinity"]],
        ["Number", ["double", "Infinity"]],
      ],
      returns: "Number",
      rest: true,
      native: true,
    },
    { method: "random", final: true, returns: "Number", native: true },
  ],
  instance: [],
};
