import type { ClassDecl } from "./declare.js";

export const ArrayClass = {
  name: "Array",
  super: "Object",
  init: { rest: true, native: true },
  classInit: { avmplus: true },
  static: [
    { const: "CASEINSENSITIVE", type: "uint", value: ["int", 1] },
    { const: "DESCENDING", type: "uint", value: ["int", 2] },
    { const: "UNIQUESORT", type: "uint", value: ["int", 4] },
    { const: "RETURNINDEXEDARRAY", type: "uint", value: ["int", 8] },
    { const: "NUMERIC", type: "uint", value: ["int", 16] },
    { const: "length", type: "int", value: ["int", 1] },
    { method: "private::_join", final: true, params: ["*", "*"], returns: "String", native: true },
    { method: "private::_pop", final: true, params: ["*"], native: true },
    { method: "private::_reverse", final: true, params: ["*"], native: true },
    {
      method: "private::_concat",
      final: true,
      params: ["*", "Array"],
      returns: "Array",
      native: true,
    },
    { method: "private::_shift", final: true, params: ["*"], native: true },
    {
      method: "private::_slice",
      final: true,
      params: ["*", "Number", "Number"],
      returns: "Array",
      native: true,
    },
    {
      method: "private::_unshift",
      final: true,
      params: ["*", "Array"],
      returns: "uint",
      native: true,
    },
    {
      method: "private::_splice",
      final: true,
      params: ["*", "Array"],
      returns: "Array",
      native: true,
    },
    { method: "private::_sort", final: true, params: ["*", "Array"], native: true },
    { method: "private::_sortOn", final: true, params: ["*", "*", "*"], native: true },
    {
      method: "private::_indexOf",
      final: true,
      params: ["*", "*", "int"],
      returns: "int",
      native: true,
    },
    {
      method: "private::_lastIndexOf",
      final: true,
      params: ["*", "*", ["int", ["int", 0]]],
      returns: "int",
      native: true,
    },
    {
      method: "private::_every",
      final: true,
      params: ["*", "Function", "*"],
      returns: "Boolean",
      native: true,
    },
    {
      method: "private::_filter",
      final: true,
      params: ["*", "Function", "*"],
      returns: "Array",
      native: true,
    },
    {
      method: "private::_forEach",
      final: true,
      params: ["*", "Function", "*"],
      returns: "void",
      native: true,
    },
    {
      method: "private::_map",
      final: true,
      params: ["*", "Function", "*"],
      returns: "Array",
      native: true,
    },
    {
      method: "private::_some",
      final: true,
      params: ["*", "Function", "*"],
      returns: "Boolean",
      native: true,
    },
  ],
  instance: [
    {
      method: "AS3::insertAt",
      params: ["int", "*"],
      returns: "void",
      native: true,
      meta: [["API", [["", "708"]]]],
    },
    { method: "AS3::removeAt", params: ["int"], native: true, meta: [["API", [["", "708"]]]] },
    { get: "length", returns: "uint", native: true },
    { set: "length", params: ["uint"], native: true },
    { method: "private::set_length", params: ["*", "uint"], native: true },
    { method: "AS3::join", params: [["*", ["undefined", null]]], returns: "String", native: true },
    { method: "AS3::pop", native: true },
    { method: "AS3::push", returns: "uint", rest: true, native: true },
    { method: "AS3::reverse", returns: "Array", native: true },
    { method: "AS3::concat", returns: "Array", rest: true, native: true },
    { method: "AS3::shift", native: true },
    {
      method: "AS3::slice",
      params: [
        ["*", ["int", 0]],
        ["*", ["double", 4294967295]],
      ],
      returns: "Array",
      native: true,
    },
    { method: "AS3::unshift", returns: "uint", rest: true, native: true },
    { method: "AS3::splice", rest: true, native: true },
    { method: "AS3::sort", rest: true, native: true },
    { method: "AS3::sortOn", params: ["*", ["*", ["int", 0]]], rest: true, native: true },
    { method: "AS3::indexOf", params: ["*", ["*", ["int", 0]]], returns: "int", native: true },
    {
      method: "AS3::lastIndexOf",
      params: ["*", ["*", ["int", 2147483647]]],
      returns: "int",
      native: true,
    },
    {
      method: "AS3::every",
      params: ["Function", ["*", ["null", null]]],
      returns: "Boolean",
      native: true,
    },
    {
      method: "AS3::filter",
      params: ["Function", ["*", ["null", null]]],
      returns: "Array",
      native: true,
    },
    {
      method: "AS3::forEach",
      params: ["Function", ["*", ["null", null]]],
      returns: "void",
      native: true,
    },
    {
      method: "AS3::map",
      params: ["Function", ["*", ["null", null]]],
      returns: "Array",
      native: true,
    },
    {
      method: "AS3::some",
      params: ["Function", ["*", ["null", null]]],
      returns: "Boolean",
      native: true,
    },
  ],
} as const satisfies ClassDecl;
