import type { ClassDecl } from "./declare.js";

export const NumberClass = {
  name: "Number",
  super: "Object",
  sealed: true,
  final: true,
  init: { params: [["*", ["int", 0]]], avmplus: true },
  classInit: { avmplus: true },
  static: [
    { const: "length", type: "int", value: ["int", 1] },
    { const: "NaN", type: "Number", value: ["double", "NaN"] },
    { const: "NEGATIVE_INFINITY", type: "Number", value: ["double", "-Infinity"] },
    { const: "POSITIVE_INFINITY", type: "Number", value: ["double", "Infinity"] },
    { const: "MIN_VALUE", type: "Number" },
    { const: "MAX_VALUE", type: "Number", value: ["double", 1.7976931348623157e308] },
    {
      const: "E",
      api: 20,
      meta: [["API", [["", "680"]]]],
      type: "Number",
      value: ["double", Math.E],
    },
    {
      const: "LN10",
      api: 20,
      meta: [["API", [["", "680"]]]],
      type: "Number",
      value: ["double", Math.LN10],
    },
    {
      const: "LN2",
      api: 20,
      meta: [["API", [["", "680"]]]],
      type: "Number",
      value: ["double", Math.LN2],
    },
    {
      const: "LOG10E",
      api: 20,
      meta: [["API", [["", "680"]]]],
      type: "Number",
      value: ["double", Math.LOG10E],
    },
    {
      const: "LOG2E",
      api: 20,
      meta: [["API", [["", "680"]]]],
      type: "Number",
      value: ["double", Math.LOG2E],
    },
    {
      const: "PI",
      api: 20,
      meta: [["API", [["", "680"]]]],
      type: "Number",
      value: ["double", Math.PI],
    },
    {
      const: "SQRT1_2",
      api: 20,
      meta: [["API", [["", "680"]]]],
      type: "Number",
      value: ["double", Math.SQRT1_2],
    },
    {
      const: "SQRT2",
      api: 20,
      meta: [["API", [["", "680"]]]],
      type: "Number",
      value: ["double", Math.SQRT2],
    },
    {
      method: "abs",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "acos",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "asin",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "atan",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "ceil",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "cos",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "exp",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "floor",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "log",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "round",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "sin",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "sqrt",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "tan",
      final: true,
      params: ["Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "atan2",
      final: true,
      params: ["Number", "Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "pow",
      final: true,
      params: ["Number", "Number"],
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "max",
      final: true,
      params: [
        ["Number", ["double", "-Infinity"]],
        ["Number", ["double", "-Infinity"]],
      ],
      returns: "Number",
      rest: true,
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "min",
      final: true,
      params: [
        ["Number", ["double", "Infinity"]],
        ["Number", ["double", "Infinity"]],
      ],
      returns: "Number",
      rest: true,
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    {
      method: "random",
      final: true,
      returns: "Number",
      native: true,
      api: 20,
      meta: [["API", [["", "680"]]]],
    },
    { const: "private::DTOSTR_FIXED", type: "int", value: ["int", 1] },
    { const: "private::DTOSTR_PRECISION", type: "int", value: ["int", 2] },
    { const: "private::DTOSTR_EXPONENTIAL", type: "int", value: ["int", 3] },
    {
      method: "private::_numberToString",
      final: true,
      params: ["Number", "int"],
      returns: "String",
      native: true,
    },
    {
      method: "private::_convert",
      final: true,
      params: ["Number", "int", "int"],
      returns: "String",
      native: true,
    },
    { method: "private::_minValue", final: true, returns: "Number", native: true },
  ],
  instance: [
    { method: "AS3::toString", params: [["*", ["int", 10]]], returns: "String", avmplus: true },
    { method: "AS3::valueOf", returns: "Number", avmplus: true },
    { method: "AS3::toExponential", params: [["*", ["int", 0]]], returns: "String", avmplus: true },
    { method: "AS3::toPrecision", params: [["*", ["int", 0]]], returns: "String", avmplus: true },
    { method: "AS3::toFixed", params: [["*", ["int", 0]]], returns: "String", avmplus: true },
  ],
} as const satisfies ClassDecl;
