// Generated by tools/thunks.ts from the declarations: regenerate, do not edit.
// Each native whose arguments need defaults or coercing, by its key, called
// through a function of its own (see tools/thunks.ts and bind.ts).

import type { AsObject, Method, Value } from "../descriptors.js";
import { NS_Public, namespace } from "../names.js";
import type { Runtime } from "../runtime.js";

export const thunks: Record<string, (rt: Runtime, f: Method) => Method> = {
  "ArgumentError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "Array#Array::set_length": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.toUint(a1));
    },
  "Array#http://adobe.com/AS3/2006/builtin::every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? a1 : null);
    };
  },
  "Array#http://adobe.com/AS3/2006/builtin::filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? a1 : null);
    };
  },
  "Array#http://adobe.com/AS3/2006/builtin::forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? a1 : null);
    };
  },
  "Array#http://adobe.com/AS3/2006/builtin::indexOf": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, a0, n > 1 ? a1 : 0);
    },
  "Array#http://adobe.com/AS3/2006/builtin::insertAt": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toInt(a0), a1);
    },
  "Array#http://adobe.com/AS3/2006/builtin::join": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "Array#http://adobe.com/AS3/2006/builtin::lastIndexOf": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, a0, n > 1 ? a1 : 2147483647);
    },
  "Array#http://adobe.com/AS3/2006/builtin::map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? a1 : null);
    };
  },
  "Array#http://adobe.com/AS3/2006/builtin::removeAt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "Array#http://adobe.com/AS3/2006/builtin::slice": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0, n > 1 ? a1 : 4294967295);
    },
  "Array#http://adobe.com/AS3/2006/builtin::some": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? a1 : null);
    };
  },
  "Array#http://adobe.com/AS3/2006/builtin::sortOn": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      const n = arguments.length;
      return f.call(this, a0, n > 1 ? a1 : 0, ...rest);
    },
  "Array#set:length": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "Array.Array::_concat": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0));
    };
  },
  "Array.Array::_every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "Array.Array::_filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "Array.Array::_forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "Array.Array::_indexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, a1, rt.toInt(a2));
    },
  "Array.Array::_lastIndexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      const n = arguments.length;
      return f.call(this, a0, a1, n > 2 ? rt.toInt(a2) : 0);
    },
  "Array.Array::_map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "Array.Array::_slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.toNumber(a1), rt.toNumber(a2));
    },
  "Array.Array::_some": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "Array.Array::_sort": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0));
    };
  },
  "Array.Array::_splice": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0));
    };
  },
  "Array.Array::_unshift": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0));
    };
  },
  "Boolean()": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "Date#Date::_get": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "Date#Date::_setTime": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#Date::_toString": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "Date#http://adobe.com/AS3/2006/builtin::setTime": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "Date#set:date": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:dateUTC": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:fullYear": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:fullYearUTC": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:hours": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:hoursUTC": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:milliseconds": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:millisecondsUTC": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:minutes": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:minutesUTC": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:month": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:monthUTC": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:seconds": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:secondsUTC": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date#set:time": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Date()": (_rt, f) =>
    function (
      this: AsObject,
      a0: Value,
      a1: Value,
      a2: Value,
      a3: Value,
      a4: Value,
      a5: Value,
      a6: Value,
    ) {
      const n = arguments.length;
      return f.call(
        this,
        n > 0 ? a0 : undefined,
        n > 1 ? a1 : undefined,
        n > 2 ? a2 : undefined,
        n > 3 ? a3 : undefined,
        n > 4 ? a4 : undefined,
        n > 5 ? a5 : undefined,
        n > 6 ? a6 : undefined,
      );
    },
  "Date.UTC": (_rt, f) =>
    function (
      this: AsObject,
      a0: Value,
      a1: Value,
      a2: Value,
      a3: Value,
      a4: Value,
      a5: Value,
      a6: Value,
      ...rest: Value[]
    ) {
      const n = arguments.length;
      return f.call(
        this,
        a0,
        a1,
        n > 2 ? a2 : 1,
        n > 3 ? a3 : 0,
        n > 4 ? a4 : 0,
        n > 5 ? a5 : 0,
        n > 6 ? a6 : 0,
        ...rest,
      );
    },
  "DefinitionError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "Error()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "Error.getErrorMessage": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "Error.throwError": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Class");
    return function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      return f.call(this, rt.coerceTo(a0, r0), rt.toUint(a1), ...rest);
    };
  },
  "EvalError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "Function#http://adobe.com/AS3/2006/builtin::apply": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined, n > 1 ? a1 : undefined);
    },
  "Function#http://adobe.com/AS3/2006/builtin::call": (_rt, f) =>
    function (this: AsObject, a0: Value, ...rest: Value[]) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined, ...rest);
    },
  "JSON.JSON::computePropertyList": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "JSON.JSON::parseCore": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "JSON.JSON::stringifySpecializedToString": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    const r1 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value, a3: Value) {
      return f.call(
        this,
        rt.coerceObject(a0),
        rt.coerceTo(a1, r0),
        rt.coerceTo(a2, r1),
        rt.coerceString(a3),
      );
    };
  },
  "JSON.parse": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceString(a0), n > 1 ? rt.coerceTo(a1, r0) : null);
    };
  },
  "JSON.stringify": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceObject(a0), n > 1 ? a1 : null, n > 2 ? a2 : null);
    },
  "Math.Math::_max": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1));
    },
  "Math.Math::_min": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1));
    },
  "Math.abs": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.acos": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.asin": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.atan": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.atan2": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1));
    },
  "Math.ceil": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.cos": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.exp": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.floor": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.log": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.max": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      const n = arguments.length;
      return f.call(
        this,
        n > 0 ? rt.toNumber(a0) : Number.NEGATIVE_INFINITY,
        n > 1 ? rt.toNumber(a1) : Number.NEGATIVE_INFINITY,
        ...rest,
      );
    },
  "Math.min": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      const n = arguments.length;
      return f.call(
        this,
        n > 0 ? rt.toNumber(a0) : Number.POSITIVE_INFINITY,
        n > 1 ? rt.toNumber(a1) : Number.POSITIVE_INFINITY,
        ...rest,
      );
    },
  "Math.pow": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1));
    },
  "Math.round": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.sin": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.sqrt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Math.tan": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Namespace()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined, n > 1 ? a1 : undefined);
    },
  "Number#http://adobe.com/AS3/2006/builtin::toExponential": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "Number#http://adobe.com/AS3/2006/builtin::toFixed": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "Number#http://adobe.com/AS3/2006/builtin::toPrecision": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "Number#http://adobe.com/AS3/2006/builtin::toString": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 10);
    },
  "Number()": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "Number.Number::_convert": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, rt.toNumber(a0), rt.toInt(a1), rt.toInt(a2));
    },
  "Number.Number::_numberToString": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toInt(a1));
    },
  "Number.abs": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.acos": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.asin": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.atan": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.atan2": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1));
    },
  "Number.ceil": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.cos": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.exp": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.floor": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.log": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.max": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      const n = arguments.length;
      return f.call(
        this,
        n > 0 ? rt.toNumber(a0) : Number.NEGATIVE_INFINITY,
        n > 1 ? rt.toNumber(a1) : Number.NEGATIVE_INFINITY,
        ...rest,
      );
    },
  "Number.min": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      const n = arguments.length;
      return f.call(
        this,
        n > 0 ? rt.toNumber(a0) : Number.POSITIVE_INFINITY,
        n > 1 ? rt.toNumber(a1) : Number.POSITIVE_INFINITY,
        ...rest,
      );
    },
  "Number.pow": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1));
    },
  "Number.round": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.sin": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.sqrt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Number.tan": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "Object#http://adobe.com/AS3/2006/builtin::hasOwnProperty": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "Object#http://adobe.com/AS3/2006/builtin::isPrototypeOf": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "Object#http://adobe.com/AS3/2006/builtin::propertyIsEnumerable": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "Object.Object::_dontEnumPrototype": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceObject(a0));
    },
  "Object.Object::_hasOwnProperty": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceString(a1));
    },
  "Object.Object::_propertyIsEnumerable": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceString(a1));
    },
  "Object.Object::_setPropertyIsEnumerable": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceString(a1), !!a2);
    },
  "QName()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined, n > 1 ? a1 : undefined);
    },
  "RangeError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "ReferenceError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "RegExp#http://adobe.com/AS3/2006/builtin::exec": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : "");
    },
  "RegExp#http://adobe.com/AS3/2006/builtin::test": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : "");
    },
  "RegExp#set:lastIndex": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "RegExp()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined, n > 1 ? a1 : undefined);
    },
  "SecurityError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "String#String::_indexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceString(a0), n > 1 ? rt.toInt(a1) : 0);
    },
  "String#String::_lastIndexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceString(a0), n > 1 ? rt.toInt(a1) : 2147483647);
    },
  "String#String::_slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toInt(a0) : 0, n > 1 ? rt.toInt(a1) : 2147483647);
    },
  "String#String::_substr": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toInt(a0) : 0, n > 1 ? rt.toInt(a1) : 2147483647);
    },
  "String#String::_substring": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toInt(a0) : 0, n > 1 ? rt.toInt(a1) : 2147483647);
    },
  "String#http://adobe.com/AS3/2006/builtin::charAt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0);
    },
  "String#http://adobe.com/AS3/2006/builtin::charCodeAt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0);
    },
  "String#http://adobe.com/AS3/2006/builtin::indexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : "undefined", n > 1 ? rt.toNumber(a1) : 0);
    },
  "String#http://adobe.com/AS3/2006/builtin::lastIndexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(
        this,
        n > 0 ? rt.coerceString(a0) : "undefined",
        n > 1 ? rt.toNumber(a1) : 2147483647,
      );
    },
  "String#http://adobe.com/AS3/2006/builtin::localeCompare": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "String#http://adobe.com/AS3/2006/builtin::match": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "String#http://adobe.com/AS3/2006/builtin::replace": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined, n > 1 ? a1 : undefined);
    },
  "String#http://adobe.com/AS3/2006/builtin::search": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "String#http://adobe.com/AS3/2006/builtin::slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "String#http://adobe.com/AS3/2006/builtin::split": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined, n > 1 ? a1 : 4294967295);
    },
  "String#http://adobe.com/AS3/2006/builtin::substr": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "String#http://adobe.com/AS3/2006/builtin::substring": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "String()": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "");
    },
  "String.String::_match": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceString(a0), a1);
    },
  "String.String::_replace": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, rt.coerceString(a0), a1, a2);
    },
  "String.String::_search": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceString(a0), a1);
    },
  "String.String::_split": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, rt.coerceString(a0), a1, rt.toUint(a2));
    },
  "SyntaxError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "TypeError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "URIError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "UninitializedError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "VerifyError()": (_rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "", n > 1 ? a1 : 0);
    },
  "Walker#walk": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceObject(a0), rt.coerceString(a1));
    },
  "Walker()": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "XML#XML::_namespace": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.toInt(a1));
    },
  "XML#http://adobe.com/AS3/2006/builtin::descendants": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "*");
    },
  "XML#http://adobe.com/AS3/2006/builtin::elements": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "*");
    },
  "XML#http://adobe.com/AS3/2006/builtin::hasOwnProperty": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "XML#http://adobe.com/AS3/2006/builtin::processingInstructions": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "*");
    },
  "XML#http://adobe.com/AS3/2006/builtin::propertyIsEnumerable": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "XML#http://adobe.com/AS3/2006/builtin::setNotification": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "XML#http://adobe.com/AS3/2006/builtin::toJSON": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "XML()": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "XML.http://adobe.com/AS3/2006/builtin::setSettings": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceObject(a0) : null);
    },
  "XML.set:ignoreComments": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "XML.set:ignoreProcessingInstructions": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "XML.set:ignoreWhitespace": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "XML.set:prettyIndent": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "XML.set:prettyPrinting": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "XMLList#XMLList::_namespace": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.toInt(a1));
    },
  "XMLList#http://adobe.com/AS3/2006/builtin::descendants": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "*");
    },
  "XMLList#http://adobe.com/AS3/2006/builtin::elements": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "*");
    },
  "XMLList#http://adobe.com/AS3/2006/builtin::hasOwnProperty": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "XMLList#http://adobe.com/AS3/2006/builtin::processingInstructions": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : "*");
    },
  "XMLList#http://adobe.com/AS3/2006/builtin::propertyIsEnumerable": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "XMLList#http://adobe.com/AS3/2006/builtin::toJSON": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "XMLList()": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : undefined);
    },
  "__AS3__.vec::Vector$double#__AS3__.vec:Vector$double::_concat": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "__AS3__.vec::Vector$double#__AS3__.vec:Vector$double::_filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceTo(a0, r0), a1);
    };
  },
  "__AS3__.vec::Vector$double#__AS3__.vec:Vector$double::_map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceTo(a0, r0), a1);
    };
  },
  "__AS3__.vec::Vector$double#__AS3__.vec:Vector$double::_slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$double#__AS3__.vec:Vector$double::_splice": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, a1, rt.coerceTo(a2, r0));
    };
  },
  "__AS3__.vec::Vector$double#__AS3__.vec:Vector$double::_spliceHelper": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value, a3: Value, a4: Value) {
      return f.call(
        this,
        rt.toUint(a0),
        rt.toUint(a1),
        rt.toUint(a2),
        rt.coerceObject(a3),
        rt.toUint(a4),
      );
    },
  "__AS3__.vec::Vector$double#__AS3__.vec:Vector$double::clamp": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toUint(a1));
    },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::indexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.toNumber(a0), n > 1 ? rt.toNumber(a1) : 0);
    },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::insertAt": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toInt(a0), rt.toNumber(a1));
    },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::join": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : ",");
    },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::lastIndexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.toNumber(a0), n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::removeAt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::some": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, a0, n > 1 ? rt.coerceObject(a1) : null);
    },
  "__AS3__.vec::Vector$double#http://adobe.com/AS3/2006/builtin::splice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1), ...rest);
    },
  "__AS3__.vec::Vector$double#set:fixed": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "__AS3__.vec::Vector$double#set:length": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "__AS3__.vec::Vector$double()": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toUint(a0) : 0, n > 1 ? !!a1 : false);
    },
  "__AS3__.vec::Vector$double.__AS3__.vec:Vector$double::_every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$double.__AS3__.vec:Vector$double::_forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$double.__AS3__.vec:Vector$double::_some": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$double.__AS3__.vec:Vector$double::_sort": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0));
    };
  },
  "__AS3__.vec::Vector$int#__AS3__.vec:Vector$int::_concat": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "__AS3__.vec::Vector$int#__AS3__.vec:Vector$int::_filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceTo(a0, r0), a1);
    };
  },
  "__AS3__.vec::Vector$int#__AS3__.vec:Vector$int::_map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceTo(a0, r0), a1);
    };
  },
  "__AS3__.vec::Vector$int#__AS3__.vec:Vector$int::_slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$int#__AS3__.vec:Vector$int::_splice": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, a1, rt.coerceTo(a2, r0));
    };
  },
  "__AS3__.vec::Vector$int#__AS3__.vec:Vector$int::_spliceHelper": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value, a3: Value, a4: Value) {
      return f.call(
        this,
        rt.toUint(a0),
        rt.toUint(a1),
        rt.toUint(a2),
        rt.coerceObject(a3),
        rt.toUint(a4),
      );
    },
  "__AS3__.vec::Vector$int#__AS3__.vec:Vector$int::clamp": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toUint(a1));
    },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::indexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.toInt(a0), n > 1 ? rt.toNumber(a1) : 0);
    },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::insertAt": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toInt(a0), rt.toInt(a1));
    },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::join": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : ",");
    },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::lastIndexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.toInt(a0), n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::removeAt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::some": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, a0, n > 1 ? rt.coerceObject(a1) : null);
    },
  "__AS3__.vec::Vector$int#http://adobe.com/AS3/2006/builtin::splice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1), ...rest);
    },
  "__AS3__.vec::Vector$int#set:fixed": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "__AS3__.vec::Vector$int#set:length": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "__AS3__.vec::Vector$int()": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toUint(a0) : 0, n > 1 ? !!a1 : false);
    },
  "__AS3__.vec::Vector$int.__AS3__.vec:Vector$int::_every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$int.__AS3__.vec:Vector$int::_forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$int.__AS3__.vec:Vector$int::_some": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$int.__AS3__.vec:Vector$int::_sort": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0));
    };
  },
  "__AS3__.vec::Vector$object#__AS3__.vec:Vector$object::_concat": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "__AS3__.vec::Vector$object#__AS3__.vec:Vector$object::_filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceTo(a0, r0), a1);
    };
  },
  "__AS3__.vec::Vector$object#__AS3__.vec:Vector$object::_map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceTo(a0, r0), a1);
    };
  },
  "__AS3__.vec::Vector$object#__AS3__.vec:Vector$object::_slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$object#__AS3__.vec:Vector$object::_splice": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, a1, rt.coerceTo(a2, r0));
    };
  },
  "__AS3__.vec::Vector$object#__AS3__.vec:Vector$object::_spliceHelper": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value, a3: Value, a4: Value) {
      return f.call(
        this,
        rt.toUint(a0),
        rt.toUint(a1),
        rt.toUint(a2),
        rt.coerceObject(a3),
        rt.toUint(a4),
      );
    },
  "__AS3__.vec::Vector$object#__AS3__.vec:Vector$object::clamp": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toUint(a1));
    },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::indexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceObject(a0), n > 1 ? rt.toNumber(a1) : 0);
    },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::insertAt": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toInt(a0), rt.coerceObject(a1));
    },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::join": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : ",");
    },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::lastIndexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceObject(a0), n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::removeAt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::some": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, a0, n > 1 ? rt.coerceObject(a1) : null);
    },
  "__AS3__.vec::Vector$object#http://adobe.com/AS3/2006/builtin::splice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1), ...rest);
    },
  "__AS3__.vec::Vector$object#set:fixed": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "__AS3__.vec::Vector$object#set:length": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "__AS3__.vec::Vector$object()": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toUint(a0) : 0, n > 1 ? !!a1 : false);
    },
  "__AS3__.vec::Vector$object.__AS3__.vec:Vector$object::_every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$object.__AS3__.vec:Vector$object::_forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$object.__AS3__.vec:Vector$object::_some": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$object.__AS3__.vec:Vector$object::_sort": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0));
    };
  },
  "__AS3__.vec::Vector$uint#__AS3__.vec:Vector$uint::_concat": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "__AS3__.vec::Vector$uint#__AS3__.vec:Vector$uint::_filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceTo(a0, r0), a1);
    };
  },
  "__AS3__.vec::Vector$uint#__AS3__.vec:Vector$uint::_map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceTo(a0, r0), a1);
    };
  },
  "__AS3__.vec::Vector$uint#__AS3__.vec:Vector$uint::_slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$uint#__AS3__.vec:Vector$uint::_splice": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, a1, rt.coerceTo(a2, r0));
    };
  },
  "__AS3__.vec::Vector$uint#__AS3__.vec:Vector$uint::_spliceHelper": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value, a3: Value, a4: Value) {
      return f.call(
        this,
        rt.toUint(a0),
        rt.toUint(a1),
        rt.toUint(a2),
        rt.coerceObject(a3),
        rt.toUint(a4),
      );
    },
  "__AS3__.vec::Vector$uint#__AS3__.vec:Vector$uint::clamp": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toNumber(a0), rt.toUint(a1));
    },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::filter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::indexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.toUint(a0), n > 1 ? rt.toNumber(a1) : 0);
    },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::insertAt": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toInt(a0), rt.toUint(a1));
    },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::join": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : ",");
    },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::lastIndexOf": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.toUint(a0), n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::map": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, rt.coerceTo(a0, r0), n > 1 ? rt.coerceObject(a1) : null);
    };
  },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::removeAt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::slice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : 0, n > 1 ? rt.toNumber(a1) : 2147483647);
    },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::some": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, a0, n > 1 ? rt.coerceObject(a1) : null);
    },
  "__AS3__.vec::Vector$uint#http://adobe.com/AS3/2006/builtin::splice": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, ...rest: Value[]) {
      return f.call(this, rt.toNumber(a0), rt.toNumber(a1), ...rest);
    },
  "__AS3__.vec::Vector$uint#set:fixed": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "__AS3__.vec::Vector$uint#set:length": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "__AS3__.vec::Vector$uint()": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toUint(a0) : 0, n > 1 ? !!a1 : false);
    },
  "__AS3__.vec::Vector$uint.__AS3__.vec:Vector$uint::_every": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$uint.__AS3__.vec:Vector$uint::_forEach": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$uint.__AS3__.vec:Vector$uint::_some": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Function");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0), a2);
    };
  },
  "__AS3__.vec::Vector$uint.__AS3__.vec:Vector$uint::_sort": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, ""), "Array");
    return function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, a0, rt.coerceTo(a1, r0));
    };
  },
  "flash.concurrent::Condition#flash.concurrent:Condition::ctor": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, "flash.concurrent"), "Mutex");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "flash.concurrent::Condition#wait": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.toNumber(a0) : -1);
    },
  "flash.concurrent::Condition()": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, "flash.concurrent"), "Mutex");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "flash.errors::EOFError()": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : "", n > 1 ? rt.toInt(a1) : 0);
    },
  "flash.errors::IOError()": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : "", n > 1 ? rt.toInt(a1) : 0);
    },
  "flash.errors::IllegalOperationError()": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : "", n > 1 ? rt.toInt(a1) : 0);
    },
  "flash.errors::MemoryError()": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : "", n > 1 ? rt.toInt(a1) : 0);
    },
  "flash.net::DynamicPropertyOutput#writeDynamicProperty": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceString(a0), a1);
    },
  "flash.net::ObjectEncoding.set:dynamicPropertyWriter": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, "flash.net"), "IDynamicPropertyWriter");
    return function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceTo(a0, r0));
    };
  },
  "flash.utils::ByteArray#atomicCompareAndSwapIntAt": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      return f.call(this, rt.toInt(a0), rt.toInt(a1), rt.toInt(a2));
    },
  "flash.utils::ByteArray#atomicCompareAndSwapLength": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toInt(a0), rt.toInt(a1));
    },
  "flash.utils::ByteArray#compress": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : "zlib");
    },
  "flash.utils::ByteArray#flash.utils:ByteArray::_compress": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "flash.utils::ByteArray#flash.utils:ByteArray::_uncompress": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "flash.utils::ByteArray#readBytes": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, "flash.utils"), "ByteArray");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      const n = arguments.length;
      return f.call(
        this,
        rt.coerceTo(a0, r0),
        n > 1 ? rt.toUint(a1) : 0,
        n > 2 ? rt.toUint(a2) : 0,
      );
    };
  },
  "flash.utils::ByteArray#readMultiByte": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toUint(a0), rt.coerceString(a1));
    },
  "flash.utils::ByteArray#readUTFBytes": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::ByteArray#set:endian": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "flash.utils::ByteArray#set:length": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::ByteArray#set:objectEncoding": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::ByteArray#set:position": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::ByteArray#set:shareable": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "flash.utils::ByteArray#uncompress": (rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? rt.coerceString(a0) : "zlib");
    },
  "flash.utils::ByteArray#writeBoolean": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "flash.utils::ByteArray#writeByte": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "flash.utils::ByteArray#writeBytes": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, "flash.utils"), "ByteArray");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      const n = arguments.length;
      return f.call(
        this,
        rt.coerceTo(a0, r0),
        n > 1 ? rt.toUint(a1) : 0,
        n > 2 ? rt.toUint(a2) : 0,
      );
    };
  },
  "flash.utils::ByteArray#writeDouble": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "flash.utils::ByteArray#writeFloat": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "flash.utils::ByteArray#writeInt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "flash.utils::ByteArray#writeMultiByte": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceString(a0), rt.coerceString(a1));
    },
  "flash.utils::ByteArray#writeShort": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "flash.utils::ByteArray#writeUTF": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "flash.utils::ByteArray#writeUTFBytes": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "flash.utils::ByteArray#writeUnsignedInt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::ByteArray.set:defaultObjectEncoding": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::Dictionary#flash.utils:Dictionary::init": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "flash.utils::Dictionary()": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? !!a0 : false);
    },
  "flash.utils::ObjectInput#readBytes": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, "flash.utils"), "ByteArray");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      const n = arguments.length;
      return f.call(
        this,
        rt.coerceTo(a0, r0),
        n > 1 ? rt.toUint(a1) : 0,
        n > 2 ? rt.toUint(a2) : 0,
      );
    };
  },
  "flash.utils::ObjectInput#readMultiByte": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.toUint(a0), rt.coerceString(a1));
    },
  "flash.utils::ObjectInput#readUTFBytes": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::ObjectInput#set:endian": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "flash.utils::ObjectInput#set:objectEncoding": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::ObjectOutput#set:endian": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "flash.utils::ObjectOutput#set:objectEncoding": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::ObjectOutput#writeBoolean": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, !!a0);
    },
  "flash.utils::ObjectOutput#writeByte": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "flash.utils::ObjectOutput#writeBytes": (rt, f) => {
    const r0 = rt.cls(namespace(NS_Public, "flash.utils"), "ByteArray");
    return function (this: AsObject, a0: Value, a1: Value, a2: Value) {
      const n = arguments.length;
      return f.call(
        this,
        rt.coerceTo(a0, r0),
        n > 1 ? rt.toUint(a1) : 0,
        n > 2 ? rt.toUint(a2) : 0,
      );
    };
  },
  "flash.utils::ObjectOutput#writeDouble": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "flash.utils::ObjectOutput#writeFloat": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toNumber(a0));
    },
  "flash.utils::ObjectOutput#writeInt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "flash.utils::ObjectOutput#writeMultiByte": (rt, f) =>
    function (this: AsObject, a0: Value, a1: Value) {
      return f.call(this, rt.coerceString(a0), rt.coerceString(a1));
    },
  "flash.utils::ObjectOutput#writeShort": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "flash.utils::ObjectOutput#writeUTF": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "flash.utils::ObjectOutput#writeUTFBytes": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.coerceString(a0));
    },
  "flash.utils::ObjectOutput#writeUnsignedInt": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toUint(a0));
    },
  "flash.utils::Proxy#http://www.adobe.com/2006/actionscript/flash/proxy::nextName": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "flash.utils::Proxy#http://www.adobe.com/2006/actionscript/flash/proxy::nextNameIndex": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "flash.utils::Proxy#http://www.adobe.com/2006/actionscript/flash/proxy::nextValue": (rt, f) =>
    function (this: AsObject, a0: Value) {
      return f.call(this, rt.toInt(a0));
    },
  "int#http://adobe.com/AS3/2006/builtin::toExponential": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "int#http://adobe.com/AS3/2006/builtin::toFixed": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "int#http://adobe.com/AS3/2006/builtin::toPrecision": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "int#http://adobe.com/AS3/2006/builtin::toString": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 10);
    },
  "int()": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "uint#http://adobe.com/AS3/2006/builtin::toExponential": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "uint#http://adobe.com/AS3/2006/builtin::toFixed": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "uint#http://adobe.com/AS3/2006/builtin::toPrecision": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
  "uint#http://adobe.com/AS3/2006/builtin::toString": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 10);
    },
  "uint()": (_rt, f) =>
    function (this: AsObject, a0: Value) {
      const n = arguments.length;
      return f.call(this, n > 0 ? a0 : 0);
    },
};
