import type { ClassDecl } from "./declare.js";

export const XMLListClass = {
  name: "XMLList",
  super: "Object",
  final: true,
  init: { params: [["*", ["undefined", null]]], avmplus: true },
  classInit: { avmplus: true },
  static: [{ const: "length", value: ["int", 1] }],
  instance: [
    { method: "AS3::toString", returns: "String", native: true },
    { method: "AS3::valueOf", returns: "XMLList", avmplus: true },
    {
      method: "AS3::hasOwnProperty",
      override: true,
      params: [["*", ["undefined", null]]],
      returns: "Boolean",
      native: true,
    },
    {
      method: "AS3::propertyIsEnumerable",
      override: true,
      params: [["*", ["undefined", null]]],
      returns: "Boolean",
      native: true,
    },
    { method: "AS3::attribute", params: ["*"], returns: "XMLList", native: true },
    { method: "AS3::attributes", returns: "XMLList", native: true },
    { method: "AS3::child", params: ["*"], returns: "XMLList", native: true },
    { method: "AS3::children", returns: "XMLList", native: true },
    { method: "AS3::comments", returns: "XMLList", native: true },
    { method: "AS3::contains", params: ["*"], returns: "Boolean", native: true },
    { method: "AS3::copy", returns: "XMLList", native: true },
    {
      method: "AS3::descendants",
      params: [["*", ["string", "*"]]],
      returns: "XMLList",
      native: true,
    },
    { method: "AS3::elements", params: [["*", ["string", "*"]]], returns: "XMLList", native: true },
    { method: "AS3::hasComplexContent", returns: "Boolean", native: true },
    { method: "AS3::hasSimpleContent", returns: "Boolean", native: true },
    { method: "AS3::length", returns: "int", native: true },
    { method: "AS3::name", returns: "Object", native: true },
    { method: "AS3::normalize", returns: "XMLList", native: true },
    { method: "AS3::parent", native: true },
    {
      method: "AS3::processingInstructions",
      params: [["*", ["string", "*"]]],
      returns: "XMLList",
      native: true,
    },
    { method: "AS3::text", returns: "XMLList", native: true },
    { method: "AS3::toXMLString", returns: "String", native: true },
    { method: "AS3::addNamespace", params: ["*"], returns: "XML", native: true },
    { method: "AS3::appendChild", params: ["*"], returns: "XML", native: true },
    { method: "AS3::childIndex", returns: "int", native: true },
    { method: "AS3::inScopeNamespaces", returns: "Array", native: true },
    { method: "AS3::insertChildAfter", params: ["*", "*"], native: true },
    { method: "AS3::insertChildBefore", params: ["*", "*"], native: true },
    { method: "AS3::nodeKind", returns: "String", native: true },
    { method: "private::_namespace", params: ["*", "int"], native: true },
    { method: "AS3::namespace", params: [["*", ["null", null]]], arguments: true, avmplus: true },
    { method: "AS3::localName", returns: "Object", native: true },
    { method: "AS3::namespaceDeclarations", returns: "Array", native: true },
    { method: "AS3::prependChild", params: ["*"], returns: "XML", native: true },
    { method: "AS3::removeNamespace", params: ["*"], returns: "XML", native: true },
    { method: "AS3::replace", params: ["*", "*"], returns: "XML", native: true },
    { method: "AS3::setChildren", params: ["*"], returns: "XML", native: true },
    { method: "AS3::setLocalName", params: ["*"], returns: "void", native: true },
    { method: "AS3::setName", params: ["*"], returns: "void", native: true },
    { method: "AS3::setNamespace", params: ["*"], returns: "void", native: true },
    { method: "AS3::toJSON", params: ["String"], avmplus: true },
  ],
} as const satisfies ClassDecl;
